version: '2'
services:
  db:
    image: postgres
    env_file:
      - .env.postgres
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    ports:
      - 5433:5432

  api:
    build: .
    volumes:
      - ./:/app
      - ./appvolumes/:/appvolumes
    ports:
      - 8080:8888
    env_file:
      - .env.api
    links:
      - db:db

  image_server:
    image: kyma/docker-nginx
    ports:
      - 80:80
    volumes:
      - ./appvolumes:/var/www/appvolumes
